(function() {function g(a){throw a;}var h=void 0,j=!0,k=null,l=!1;function o(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,t=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){return a!==h}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){a=ba(a);return"object"==a||"array"==a||"function"==a}Math.floor(2147483648*Math.random()).toString(36);function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return y.apply(k,arguments)}function ia(a,b){function c(){}c.prototype=b.prototype;a.Yc=b.prototype;a.prototype=new c};function ja(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};var ka=/[\[\].#$\/]/,la=/[\[\].#$]/;function ma(a){return x(a)&&0!==a.length&&!ka.test(a)}function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function na(a,b,c){(!c||u(b))&&oa(B(a,1,c),b)}
function oa(a,b){u(b)||g(Error(a+"contains undefined."));"function"==ba(b)&&g(Error(a+"contains a function."));x(b)&&b.length>10485760/3&&10485760<ja(b).length&&g(Error(a+"contains a string greater than 10485760 utf8 bytes ('"+b.substring(0,50)+"...')"));if(ea(b))for(var c in b)b.hasOwnProperty(c)&&(".priority"!==c&&".value"!==c&&!ma(c)&&g(Error(a+"contains an invalid key ("+c+').  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),oa(a,b[c]))}
function pa(a,b,c,d){(!d||u(c))&&c!==k&&!da(c)&&!x(c)&&g(Error(B(a,b,d)+"must be a valid firebase priority (null or a string.)"))}function D(a,b,c,d){(!d||u(c))&&"function"!=ba(c)&&g(Error(B(a,b,d)+"must be a valid function."))}function qa(a,b){switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(B(a,1,l)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}
function ra(a,b){u(b)&&!ma(b)&&g(Error(B(a,2,j)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}function sa(a,b){(!x(b)||0===b.length||la.test(b))&&g(Error(B(a,1,l)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function E(a,b){".info"===F(b)&&g(Error(a+" failed: Can't modify data under /.info/"))}function ta(a,b){x(b)||g(Error(B(a,1,l)+"must be a valid firebase username."))}
function ua(a,b,c){x(c)||g(Error(B(a,b,l)+"must be a valid credential (a string)."))}function B(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:G(l,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}a+=" failed: ";c&&(a+="If provided, ");return a+(d+" argument ")};function wa(a){a=""+a;if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function xa(){this.qb=h}
function ya(a,b,c){switch(typeof b){case "string":za(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==k){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ya(a,a.qb?a.qb.call(b,""+f,e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),za(f,
c),c.push(":"),ya(a,a.qb?a.qb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var Aa={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function za(a,b){b.push('"',a.replace(Ba,function(a){if(a in Aa)return Aa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Aa[a]=e+b.toString(16)}),'"')};function H(a){if("undefined"!==typeof JSON&&u(JSON.stringify))a=JSON.stringify(a);else{var b=[];ya(new xa,a,b);a=b.join("")}return a};function I(a,b,c,d,e,f,i){this.j=a;this.path=b;this.ea=c;this.ka=Ca.test(d)?Number(d):d;this.xa=e;this.qa=Ca.test(f)?Number(f):f;this.pa=i;u(this.ka)&&u(this.qa)&&u(this.ea)&&g("fb.api.Query: Can't combine startAt(), endAt(), and limit().")}I.prototype.Gb=function(a,b){A("fb.api.Query.on",2,2,arguments.length);qa("fb.api.Query.on",a);D("fb.api.Query.on",2,b,l);this.j.ab(this,a,b);return b};I.prototype.on=I.prototype.Gb;
I.prototype.Fb=function(a,b){A("fb.api.Query.off",2,2,arguments.length);qa("fb.api.Query.off",a);D("fb.api.Query.off",2,b,l);this.j.pb(this,a,b)};I.prototype.off=I.prototype.Fb;I.prototype.Kc=function(a,b){function c(f){e&&(e=l,d.Fb(a,c),b(f))}A("fb.api.Query.once",2,2,arguments.length);qa("fb.api.Query.once",a);D("fb.api.Query.once",2,b,l);var d=this,e=j;this.Gb(a,c)};I.prototype.once=I.prototype.Kc;
I.prototype.rc=function(a){A("fb.api.Query.limit",1,1,arguments.length);(!da(a)||Math.floor(a)!==a||0>=a)&&g("fb.api.Query.limit: First argument must be a positive integer.");return new I(this.j,this.path,a,this.ka,this.xa,this.qa,this.pa)};I.prototype.limit=I.prototype.rc;I.prototype.Sc=function(a,b){A("fb.api.Query.startAt",0,2,arguments.length);pa("fb.api.Query.startAt",1,a,j);ra("fb.api.Query.startAt",b);u(a)||(b=a=k);return new I(this.j,this.path,this.ea,a,b,this.qa,this.pa)};
I.prototype.startAt=I.prototype.Sc;I.prototype.mc=function(a,b){A("fb.api.Query.endAt",0,2,arguments.length);pa("fb.api.Query.endAt",1,a,j);ra("fb.api.Query.endAt",b);return new I(this.j,this.path,this.ea,this.ka,this.xa,a,b)};I.prototype.endAt=I.prototype.mc;function Da(a){var b={};u(a.ka)&&(b.sp=a.ka);u(a.xa)&&(b.sn=a.xa);u(a.qa)&&(b.ep=a.qa);u(a.pa)&&(b.en=a.pa);u(a.ea)&&(b.l=a.ea);return b}I.prototype.ta=function(){var a=Ea(Da(this));return"{}"===a?"default":a};function J(a){if(a instanceof J)return a;if(1==arguments.length){this.k=a.split("/");for(var b=0,c=0;c<this.k.length;c++)0<this.k[c].length&&(this.k[b]=this.k[c],b++);this.k.length=b;this.R=0}else this.k=arguments[0],this.R=arguments[1]}function F(a){return a.R>=a.k.length?k:a.k[a.R]}function K(a){var b=a.R;b<a.k.length&&b++;return new J(a.k,b)}function Fa(a){return a.R<a.k.length?a.k[a.k.length-1]:k}
J.prototype.toString=function(){for(var a="",b=this.R;b<this.k.length;b++)""!==this.k[b]&&(a+="/"+this.k[b]);return a};J.prototype.parent=function(){if(this.R>=this.k.length)return k;for(var a=[],b=this.R;b<this.k.length-1;b++)a.push(this.k[b]);return new J(a,0)};J.prototype.A=function(a){for(var b=[],c=this.R;c<this.k.length;c++)b.push(this.k[c]);if(a instanceof J)for(c=a.R;c<a.k.length;c++)b.push(a.k[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new J(b,0)};
J.prototype.c=function(){return this.R>=this.k.length};function Ga(a,b){var c=F(a);if(c===k)return b;if(c===F(b))return Ga(K(a),K(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")};function Ha(){this.children={};this.Bb=0;this.value=k}function Ia(a,b,c){this.fb=a?a:"";this.Va=b?b:k;this.m=c?c:new Ha}function L(a,b){for(var c=b instanceof J?b:new J(b),d=a,e;(e=F(c))!==k;)d=new Ia(e,d,e in d.m.children?d.m.children[e]:new Ha),c=K(c);return d}q=Ia.prototype;q.i=function(){return this.m.value};function M(a,b){G("undefined"!==typeof b);a.m.value=b;Ja(a)}q.eb=function(){return 0<this.m.Bb};q.c=function(){return this.i()===k&&!this.eb()};
q.z=function(a){for(var b in this.m.children)a(new Ia(b,this,this.m.children[b]))};function Ka(a,b,c,d){c&&!d&&b(a);a.z(function(a){Ka(a,b,j,d)});c&&d&&b(a)}function La(a,b){for(var c=a.parent();c!==k;){if(b(c))return j;c=c.parent()}return l}q.path=function(){return new J(this.Va===k?this.fb:this.Va.path()+"/"+this.fb)};q.name=o("fb");q.parent=o("Va");
function Ja(a){if(a.Va!==k){var b=a.Va,c=a.fb,d=a.c(),e=c in b.m.children;d&&e?(delete b.m.children[c],b.m.Bb--,Ja(b)):!d&&!e&&(b.m.children[c]=a.m,b.m.Bb++,Ja(b))}};function N(a,b){this.za=a?a:Ma;this.S=b?b:Na}function Ma(a,b){return a<b?-1:a>b?1:0}q=N.prototype;q.Y=function(a,b){return new N(this.za,this.S.Y(a,b,this.za).copy(k,k,l,k,k))};q.remove=function(a){return new N(this.za,this.S.remove(a,this.za).copy(k,k,l,k,k))};q.get=function(a){for(var b,c=this.S;!c.c();){b=this.za(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return k};
function Oa(a,b){for(var c,d=a.S,e=k;!d.c();){c=a.za(b,d.key);if(0===c){if(d.left.c())return e?e.key:k;for(d=d.left;!d.right.c();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g("Attempted to find predecessor key for a nonexistent key.  What gives?")}q.c=function(){return this.S.c()};q.count=function(){return this.S.count()};q.Ra=function(){return this.S.Ra()};q.Da=function(){return this.S.Da()};q.da=function(a){return this.S.da(a)};q.ua=function(a){return this.S.ua(a)};
q.Ba=function(a){return new Pa(this.S,a)};function Pa(a,b){this.bc=b;for(this.gb=[];!a.c();)this.gb.push(a),a=a.left}function Qa(a){if(0===a.gb.length)return k;var b=a.gb.pop(),c;c=a.bc?a.bc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.c();)a.gb.push(b),b=b.left;return c}function Ra(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=k?c:j;this.left=d!=k?d:Na;this.right=e!=k?e:Na}q=Ra.prototype;
q.copy=function(a,b,c,d,e){return new Ra(a!=k?a:this.key,b!=k?b:this.value,c!=k?c:this.color,d!=k?d:this.left,e!=k?e:this.right)};q.count=function(){return this.left.count()+1+this.right.count()};q.c=p(l);q.da=function(a){return this.left.da(a)||a(this.key,this.value)||this.right.da(a)};q.ua=function(a){return this.right.ua(a)||a(this.key,this.value)||this.left.ua(a)};function Sa(a){return a.left.c()?a:Sa(a.left)}q.Ra=function(){return Sa(this).key};
q.Da=function(){return this.right.c()?this.key:this.right.Da()};q.Y=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(k,k,k,e.left.Y(a,b,c),k):0===d?e.copy(k,b,k,k,k):e.copy(k,k,k,k,e.right.Y(a,b,c));return Ta(e)};function Ua(a){if(a.left.c())return Na;!a.left.w()&&!a.left.left.w()&&(a=Va(a));a=a.copy(k,k,k,Ua(a.left),k);return Ta(a)}
q.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.c()&&!c.left.w()&&!c.left.left.w()&&(c=Va(c)),c=c.copy(k,k,k,c.left.remove(a,b),k);else{c.left.w()&&(c=Wa(c));!c.right.c()&&!c.right.w()&&!c.right.left.w()&&(c=Xa(c),c.left.left.w()&&(c=Wa(c),c=Xa(c)));if(0===b(a,c.key)){if(c.right.c())return Na;d=Sa(c.right);c=c.copy(d.key,d.value,k,k,Ua(c.right))}c=c.copy(k,k,k,k,c.right.remove(a,b))}return Ta(c)};q.w=o("color");
function Ta(a){a.right.w()&&!a.left.w()&&(a=Ya(a));a.left.w()&&a.left.left.w()&&(a=Wa(a));a.left.w()&&a.right.w()&&(a=Xa(a));return a}function Va(a){a=Xa(a);a.right.left.w()&&(a=a.copy(k,k,k,k,Wa(a.right)),a=Ya(a),a=Xa(a));return a}function Ya(a){return a.right.copy(k,k,a.color,a.copy(k,k,j,k,a.right.left),k)}function Wa(a){return a.left.copy(k,k,a.color,k,a.copy(k,k,j,a.left.right,k))}
function Xa(a){var b,c;b=a.left.copy(k,k,!a.left.color,k,k);c=a.right.copy(k,k,!a.right.color,k,k);return a.copy(k,k,!a.color,b,c)}function Za(){}q=Za.prototype;q.copy=function(){return this};q.Y=function(a,b){return new Ra(a,b,h,h,h)};q.remove=function(){return this};q.get=p(k);q.count=p(0);q.c=p(j);q.da=p(l);q.ua=p(l);q.Ra=p(k);q.Da=p(k);q.w=p(l);var Na=new Za;var $a=/^[a-zA-Z0-9\-_.!~*'()]*$/;function ab(a){a=""+a;return!$a.test(a)?encodeURIComponent(a):a};function bb(){};function cb(){this.n=[];this.Ab=[];this.ic=[];this.jb=[];this.jb[0]=128;for(var a=1;64>a;++a)this.jb[a]=0;this.reset()}ia(cb,bb);cb.prototype.reset=function(){this.n[0]=1732584193;this.n[1]=4023233417;this.n[2]=2562383102;this.n[3]=271733878;this.n[4]=3285377520;this.Mb=this.Na=0};
function db(a,b){var c;c||(c=0);for(var d=a.ic,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.n[0];for(var i=a.n[1],m=a.n[2],n=a.n[3],r=a.n[4],s,e=0;80>e;e++)40>e?20>e?(f=n^i&(m^n),s=1518500249):(f=i^m^n,s=1859775393):60>e?(f=i&m|n&(i|m),s=2400959708):(f=i^m^n,s=3395469782),f=(c<<5|c>>>27)+f+r+s+d[e]&4294967295,r=n,n=m,m=(i<<30|i>>>2)&4294967295,i=c,c=f;a.n[0]=a.n[0]+c&4294967295;a.n[1]=a.n[1]+i&
4294967295;a.n[2]=a.n[2]+m&4294967295;a.n[3]=a.n[3]+n&4294967295;a.n[4]=a.n[4]+r&4294967295}cb.prototype.update=function(a,b){u(b)||(b=a.length);var c=this.Ab,d=this.Na,e=0;if(x(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(db(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(db(this,c),d=0);this.Na=d;this.Mb+=b};var eb,fb,gb,hb;function ib(){return t.navigator?t.navigator.userAgent:k}hb=gb=fb=eb=l;var jb;if(jb=ib()){var kb=t.navigator;eb=0==jb.indexOf("Opera");fb=!eb&&-1!=jb.indexOf("MSIE");gb=!eb&&-1!=jb.indexOf("WebKit");hb=!eb&&!gb&&"Gecko"==kb.product}var lb=fb,mb=hb,nb=gb;var ob;if(eb&&t.opera){var pb=t.opera.version;"function"==typeof pb&&pb()}else mb?ob=/rv\:([^\);]+)(\)|;)/:lb?ob=/MSIE\s+([^\);]+)(\)|;)/:nb&&(ob=/WebKit\/(\S+)/),ob&&ob.exec(ib());var qb=k,rb=k;
function sb(a,b){ca(a)||g(Error("encodeByteArray takes an array as a parameter"));if(!qb){qb={};rb={};for(var c=0;65>c;c++)qb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),rb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?rb:qb,d=[],e=0;e<a.length;e+=3){var f=a[e],i=e+1<a.length,m=i?a[e+1]:0,n=e+2<a.length,r=n?a[e+2]:0,s=f>>2,f=(f&3)<<4|m>>4,m=(m&15)<<2|r>>6,r=r&63;n||(r=64,i||(m=64));d.push(c[s],c[f],c[m],c[r])}return d.join("")}
;var tb=function(){var a=1;return function(){return a++}}();function G(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function wb(a){var b=ja(a),a=new cb;a.update(b);var b=[],c=8*a.Mb;56>a.Na?a.update(a.jb,56-a.Na):a.update(a.jb,64-(a.Na-56));for(var d=63;56<=d;d--)a.Ab[d]=c&255,c/=256;db(a,a.Ab);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.n[d]>>e&255;return sb(b)}
function xb(){for(var a="",b=0;b<arguments.length;b++)a=ca(arguments[b])?a+xb.apply(k,arguments[b]):"object"===typeof arguments[b]?a+H(arguments[b]):a+arguments[b],a+=" ";return a}var yb=k;function O(){if(yb){var a=xb.apply(k,arguments);yb(a)}}function zb(){if("undefined"!==typeof console){var a=xb.apply(k,arguments);console.log("FIREBASE INTERNAL ERROR: "+a)}}var Ca=/^[\-+]?[0-9]*\.?[0-9]+$/;
function Ab(a){if("complete"===document.readyState)a();else{var b=l,c=function(){document.body?b||(b=j,a()):setTimeout(c,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",c,l),window.addEventListener("load",c,l)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&c()},l),window.attachEvent("onload",c,l))}}function Bb(a,b){return a!==b?a===k?-1:b===k?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}
var Cb=0;function Ea(a){if("object"!==typeof a||a===k)return H(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=H(b[d]),c+=":",c+=Ea(a[b[d]]);return c+"}"};function Db(a,b){this.la=a;G(this.la!==k,"LeafNode shouldn't be created with null value.");this.Ha="undefined"!==typeof b?b:k}q=Db.prototype;q.Z=p(j);q.g=o("Ha");q.yb=function(a){return new Db(this.la,a)};q.F=function(){return P};q.D=function(a){return F(a)===k?this:P};q.P=p(k);q.v=function(a,b){return(new Q(new N,this.Ha)).v(a,b)};q.Za=function(a,b){var c=F(a);return c===k?b:this.v(c,P.Za(K(a),b))};q.c=p(l);q.T=function(a){return a&&this.g()!==k?{".value":this.i(),".priority":""+this.g()}:this.i()};
q.hash=function(){var a="";this.g()!==k&&(a+="priority:"+this.g()+":");a+=typeof this.la+":"+this.la;return wb(a)};q.i=o("la");q.toString=function(){return"string"===typeof this.la?'"'+this.la+'"':this.la};function Q(a,b){this.O=a||new N;this.Ha="undefined"!==typeof b?b:k}q=Q.prototype;q.Z=p(l);q.g=o("Ha");q.yb=function(a){return new Q(this.O,a)};q.v=function(a,b){var c=this.O.remove(a);b&&b.c()&&(b=k);b!==k&&(c=c.Y(a,b));return b&&b.g()!==k?new Eb(c,k,this.Ha):new Q(c,this.Ha)};q.Za=function(a,b){var c=F(a);if(c===k)return b;var d=this.F(c).Za(K(a),b);return this.v(c,d)};q.c=function(){return this.O.c()};var Fb=/^\d+$/;q=Q.prototype;
q.T=function(a){if(this.c())return k;var b={},c=0,d=0,e=j;this.z(function(f,i){b[f]=i.T(a);c++;e&&Fb.test(f)?d=Math.max(d,Number(f)):e=l});if(!a&&e&&d<2*c){var f=[],i;for(i in b)f[i]=b[i];return f}a&&this.g()!==k&&(b[".priority"]=""+this.g());return b};q.hash=function(){var a="";this.g()!==k&&(a+="priority:"+this.g()+":");this.z(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":wb(a)};q.F=function(a){a=this.O.get(a);return a===k?P:a};
q.D=function(a){var b=F(a);return b===k?this:this.F(b).D(K(a))};q.P=function(a){return Oa(this.O,a)};q.Tb=function(){return this.O.Ra()};q.Vb=function(){return this.O.Da()};q.z=function(a){return this.O.da(a)};q.Db=function(a){return this.O.ua(a)};q.Ba=function(){return this.O.Ba()};q.toString=function(){var a="{",b=j;this.z(function(c,d){b?b=l:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var P=new Q(new N);function Eb(a,b,c){Q.call(this,a,c);b===k&&(b=new N(Gb),a.da(function(a,c){b=b.Y({name:a,fa:c.g()},c)}));this.wa=b}ia(Eb,Q);q=Eb.prototype;q.v=function(a,b){var c=this.F(a),d=this.O,e=this.wa;c!==k&&(d=d.remove(a),e=e.remove({name:a,fa:c.g()}));b&&b.c()&&(b=k);b!==k&&(d=d.Y(a,b),e=e.Y({name:a,fa:b.g()},b));return new Eb(d,e,this.g())};q.P=function(a,b){var c=Oa(this.wa,{name:a,fa:b.g()});return c?c.name:k};q.z=function(a){return this.wa.da(function(b,c){return a(b.name,c)})};
q.Db=function(a){return this.wa.ua(function(b,c){return a(b.name,c)})};q.Ba=function(){return this.wa.Ba(function(a,b){return{key:a.name,value:b}})};q.Tb=function(){return this.wa.Ra().name};q.Vb=function(){return this.wa.Da().name};function R(a,b){if("object"!==typeof a)return new Db(a,b);if(a===k)return P;var c=k;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);c!==k&&(c=Ca.test(c)?Number(c):c);if(".value"in a&&a[".value"]!==k)return new Db(a[".value"],c);var c=new Q(new N,c),d;for(d in a)if(a.hasOwnProperty(d)&&"."!==d.substring(0,1)){var e=R(a[d]);if(e.Z()||!e.c())c=c.v(d,e)}return c}function Gb(a,b){return Bb(a.fa,b.fa)||(a.name!==b.name?a.name<b.name?-1:1:0)};function S(a,b){this.m=a;this.ob=b}S.prototype.T=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.m.T()};S.prototype.val=S.prototype.T;S.prototype.nc=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.m.T(j)};S.prototype.exportVal=S.prototype.nc;S.prototype.A=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);da(a)&&(a=""+a);sa("Firebase.DataSnapshot.child",a);var b=new J(a),c=this.ob.A(b);return new S(this.m.D(b),c)};
S.prototype.child=S.prototype.A;S.prototype.oc=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);sa("Firebase.DataSnapshot.hasChild",a);return!this.m.D(new J(a)).c()};S.prototype.hasChild=S.prototype.oc;S.prototype.g=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);var a=this.m.g();return a===k?a:""+a};S.prototype.getPriority=S.prototype.g;
S.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);D("Firebase.DataSnapshot.forEach",1,a,l);if(this.m.Z())return l;var b=this;return this.m.z(function(c,d){return a(new S(d,b.ob.A(c)))})};S.prototype.forEach=S.prototype.forEach;S.prototype.eb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.m.Z()?l:!this.m.c()};S.prototype.hasChildren=S.prototype.eb;
S.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.ob.name()};S.prototype.name=S.prototype.name;S.prototype.Lc=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.ob};S.prototype.ref=S.prototype.Lc;var Hb=k;"undefined"!==typeof MozWebSocket?Hb=MozWebSocket:"undefined"!==typeof WebSocket&&(Hb=WebSocket);
function Ib(a,b,c,d,e){this.L=d;this.hb=b;this.Dc=e;this.Hc=c;this.Pa=k;this.state=0;this.frames=k;this.gc=0;a=(a.rb?"wss://":"ws://")+a.host+"/"+a.Fa+".ws";O("Connecting to "+a);this.H=new Hb(a);var f=this;this.H.onopen=function(){O("Websocket connected.  Sending hello.");f.H.send("v=2")};this.H.onclose=function(){O("Websocket connection was disconnected.");f.H=k;f.close(j)};this.H.onmessage=function(a){f.H!==k&&(a=a.data,0===f.state?"ok"===a?(O("Got hello packet.  WebSocket good."),f.state=1,f.Hc()):
"kill"===a&&(O("Shutdown message received from server, likely due to unmatching version numbers."),f.Dc()):1===f.state?(f.gc=Number(a),f.state=2,f.frames=[]):2===f.state&&(f.frames.push(a),f.frames.length==f.gc&&(a="undefined"!==typeof JSON&&u(JSON.parse)?JSON.parse(f.frames.join("")):wa(f.frames.join("")),f.state=1,Jb(f),f.hb(a))))};this.H.onerror=function(){O("WebSocket error.  Closing connection.");f.close()}}
Ib.prototype.send=function(a){Jb(this);a=H(a);a=Kb(a,16384);this.H.send(""+a.length);for(var b=0;b<a.length;b++)this.H.send(a[b])};Ib.prototype.close=function(a){if(!this.Oa&&(this.Oa=j,a||O("Closing WebSocket."),this.Pa&&(clearTimeout(this.Pa),this.Pa=k),this.H&&(this.H.close(),this.H=k),this.L))this.L(),this.L=k};function Jb(a){clearTimeout(a.Pa);a.Pa=setInterval(function(){a.H.send("0");Jb(a)},45E3)};function Lb(){this.set={}}q=Lb.prototype;q.add=function(a,b){this.set[a]=b!==k?b:j};q.get=function(a){return this.set[a]};q.remove=function(a){delete this.set[a]};q.c=function(){for(var a in this.set)return l;return j};q.count=function(){var a=0,b;for(b in this.set)a++;return a};var Mb="pLPCommand",Nb="pRTLPCB";
function Ob(a,b,c,d,e){this.Sa=(a.rb?"https://":"http://")+a.host+"/"+a.Fa+".lp";this.Nb=0;this.L=d;this.wc=new Pb(b);this.Oa=l;var f=this;this.oa=setTimeout(function(){O("Timed out trying to connect.");f.close();f.oa=k},3E4);Ab(function(){if(!f.Oa){f.va=new Qb(function(a,b,d){if(f.va)if(f.oa&&(clearTimeout(f.oa),f.oa=k),"start"==a){c();a=f.va;a.uc=b;a.vc=d;for(a.zb=j;Rb(a););f.Ea=document.createElement("iframe");f.Ea.src=f.Sa+"?disconn=t&id="+b+"&pw="+d;f.Ea.style.display="none";document.body.appendChild(f.Ea)}else"reset"==
a?(O("Got Server RESET packet."),f.close()):"shutdown"==a&&(O("Shutdown message received from server, likely due to unmatching version numbers."),e())},function(a,b){var c=f.wc;for(c.kb[a]=b;c.kb[c.cb];){var d=c.kb[c.cb];delete c.kb[c.cb];for(var e=0;e<d.length;e++)d[e]&&c.tc(d[e]);c.cb++}},function(){f.close()},f.Sa);var a=f.Sa+"?start=t&ser="+Math.floor(1E8*Math.random())+"&v=2";O("Connecting via long-poll to "+a);Sb(f.va,a,function(){})}})}
Ob.prototype.close=function(){if(!this.Oa&&(this.Oa=j,O("Closing long-poll connection."),this.va&&(this.va.close(),this.va=k),this.Ea&&(document.body.removeChild(this.Ea),this.Ea=k),this.L&&(this.L(),this.L=k),this.oa))clearTimeout(this.oa),this.oa=k};Ob.prototype.send=function(a){for(var a=H(a),a=sb(ja(a),j),a=Kb(a,1840),b=0;b<a.length;b++){var c=this.va;c.Xa.push({Qc:this.Nb,Tc:a.length,Ob:a[b]});c.zb&&Rb(c);this.Nb++}};function Pb(a){this.tc=a;this.kb=[];this.cb=0}
function Qb(a,b,c,d){this.Sa=d;this.L=c;this.Ib=new Lb;this.Xa=[];this.Cb=Math.floor(1E8*Math.random());c=tb();window[Mb+c]=a;window[Nb+c]=b;a=document.createElement("iframe");a.style.display="none";document.body?document.body.appendChild(a):g("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");a.contentDocument?a.ca=a.contentDocument:a.contentWindow?a.ca=a.contentWindow.document:a.document&&(a.ca=a.document);this.$=a;a="<html><body><script>\nfunction "+
Mb+'(c, a1, a2, a3, a4) {\nparent.window["'+Mb+c+'"](c, a1, a2, a3, a4);\n}\nfunction '+Nb+'(pN, data) {\nparent.window["'+Nb+c+'"](pN, data);\n}\n<\/script></body></html>\n';this.$.ca.open();this.$.ca.write(a);this.$.ca.close()}Qb.prototype.close=function(){this.zb=l;this.$&&(this.$.ca.body.innerHTML="",document.body.removeChild(this.$),this.$=k);var a=this.L;a&&(this.L=k,a())};
function Rb(a){if(a.zb&&a.Ib.count()<(0<a.Xa.length?2:1)){a.Cb++;for(var b=a.Sa+"?id="+a.uc+"&pw="+a.vc+"&ser="+a.Cb,c="",d=0;0<a.Xa.length;)if(1870>=a.Xa[0].Ob.length+30+c.length){var e=a.Xa.shift(),c=c+"&seg"+d+"="+e.Qc+"&ts"+d+"="+e.Tc+"&d"+d+"="+e.Ob;d++}else break;Tb(a,b+c,a.Cb);return j}return l}function Tb(a,b,c){function d(){a.Ib.remove(c);Rb(a)}a.Ib.add(c);var e=setTimeout(d,25E3);Sb(a,b,function(){clearTimeout(e);d()})}
function Sb(a,b,c){setTimeout(function(){try{var d=a.$.ca.createElement("script");d.type="text/javascript";d.async=j;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=k,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){O("Long-poll script failed to load.");a.close()};a.$.ca.body.appendChild(d)}catch(e){}},1)}
function Kb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c};function Ub(a,b,c,d,e){this.ha=a;this.Ta=b;this.V=c;this.B=d;this.Ga=e;this.G=0;this.Qa=k;this.J=0;this.$a=k;if(Hb!==k){O("CHOOSER: Starting WebSocket connection.");G(Hb!==k,"WebSocket isn't supported.");G(0===this.J,"webSocketState should be START.");G(2!==this.G,"longPollState should not be CONNECTED");this.J=1;try{this.$a=new Ib(this.ha,this.Ta,y(this.Ic,this),y(this.Jc,this),this.Ga)}catch(f){zb("WebSocket constructor threw exception: "+f.toString()),Vb(this)}}else Vb(this);if(3!==this.J){O("CHOOSER: Trying long-poll connection in 450ms.");
var i=this;setTimeout(function(){Wb(i)},450)}else Wb(this)}q=Ub.prototype;q.Ic=function(){O("CHOOSER: WebSocket connection connected.");1===this.J||zb("webSocketState should be CONNECTING.");2===this.G?Vb(this):(this.J=2,Xb(this),this.V&&(this.V(this.$a),this.V=k))};q.Jc=function(){O("CHOOSER: WebSocket connection disconnected.");G(0!==this.J,"webSocketState should not be START.");G(3===this.G||2!==this.J,"Was CONNECTED via websocket, but long-polling wasn't canceled.");Vb(this)};
function Wb(a){0===a.G&&(O("CHOOSER: Starting Long-polling connection."),G(j,"Long-polling isn't supported."),G(2!==a.J,"webSocketState should not be CONNECTED."),a.G=1,a.Qa=new Ob(a.ha,a.Ta,y(a.Ec,a),y(a.Fc,a),a.Ga))}q.Ec=function(){O("CHOOSER: Long-polling connection connected.");1===this.G||zb("longPollState should be CONNECTING.");2===this.J?Xb(this):(this.G=2,Vb(this),this.V&&(this.V(this.Qa),this.V=k))};
q.Fc=function(){O("CHOOSER: Long-polling connection disconnected.");G(0!==this.G,"longPollState should not be START.");G(3===this.J||2!==this.G,"Was CONNECTED via long-polling, but websocket wasn't canceled.");Xb(this)};function Xb(a){3!==a.G&&(O("CHOOSER: Canceling long-polling connection."),a.G=3,a.Qa&&(a.Qa.close(),a.Qa=k),Yb(a))}function Vb(a){3!==a.J&&(O("CHOOSER: Canceling websocket connection."),a.J=3,a.$a&&(a.$a.close(),a.$a=k),0===a.G&&Wb(a),Yb(a))}
function Yb(a){3===a.J&&3===a.G&&a.B&&(O("CHOOSER: Both websocket and long-polling were canceled.  Connection lost."),a.B(),a.B=k)}q.close=function(){Xb(this);Vb(this);this.B&&(this.B(),this.B=k)};function T(a,b,c,d,e){this.Ta=b;this.V=c;this.B=d;this.Ga=e;this.ia={};this.Pc=0;this.lb=[];this.ya=0;b=y(this.Gc,this);c=y(this.yc,this);d=y(this.zc,this);e=y(this.Ac,this);this.Aa=new Ub(a,b,c,d,e)}q=T.prototype;q.ja=function(a,b,c,d){var e=++this.Pc;Zb(this,{r:e,a:a,b:b});var f=this,a=setTimeout(function(){var a=f.ia[e];a&&(delete f.ia[e],a.W&&a.W.ib&&a.W.ib())},45E3);this.ia[e]={W:{hb:c,ib:d},ec:a}};
q.Gc=function(a){if("r"in a){var b=a.r,c=this.ia[b];c&&(delete this.ia[b],clearTimeout(c.ec),c.W&&c.W.hb&&c.W.hb(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a?this.Ta&&this.Ta(a.a,a.b):g("Unrecognized server packet received: "+H(a))};q.yc=function(a){O("Realtime connection established.");this.Aa=a;this.ya=1;for(a=0;a<this.lb.length;a++)Zb(this,this.lb[a]);this.lb=k;this.V&&(this.V(),this.V=k)};
q.zc=function(){this.Aa=k;0===this.ya?O("Realtime connection failed."):1===this.ya&&O("Realtime connection lost.");this.close()};q.Ac=function(){O("Connection shutdown command received. Shutting down...");this.Ga&&(this.Ga(),this.Ga=k);this.B=k;this.close()};function Zb(a,b){2===a.ya&&g("Connection has already been closed.");0===a.ya?a.lb.push(b):a.Aa.send(b)}
q.close=function(){if(2!==this.ya){O("Closing realtime connection.");this.ya=2;this.Aa&&(this.Aa.close(),this.Aa=k);this.B&&(this.B(),this.B=k);for(var a in this.ia){var b=this.ia[a];delete this.ia[a];b!==k&&(b.W&&b.W.ib&&b.W.ib(),clearTimeout(b.ec))}}};function $b(a,b,c,d){this.id=ac++;this.Ma={};this.U={};this.I=[];this.Ua=0;this.Hb={};this.X=l;this.nb=1E3;this.Yb=c;this.B=d;this.sa=[];bc(this,a,b)}var ac=0;function cc(a,b,c){var d=Ea(c);a.o("Listen on "+b+" for "+d);b={p:b};"default"!==d&&(b.q=c);a.ga.ja("l",b,k,function(){a.o("timed out on listen...")})}q=$b.prototype;
q.bb=function(a,b,c){var c={Xc:a,lc:b,Rb:l,M:c},d=k;a!==k?(this.o("Authenticating user using credential: "+b),d="u:"+a):(this.o("Authenticating admin using secret: "+b),d="admin");this.Ma[d]=c;dc(this,d)};q.wb=function(a){var b=k;a!==k?(this.o("Unauthenticating user: "+a),b="u:"+a):(this.o("Unauthenticating admin."),b="admin");delete this.Ma[b];this.X&&this.ga.ja("unauth",{user:a},function(){},function(){})};q.La=function(a,b,c){this.sa.push({action:"createuser",data:{user:a,cred:b},M:c});ec(this)};
q.Ja=function(a,b,c,d){this.sa.push({action:"setpassword",data:{user:a,cred:b,new_cred:c},M:d});ec(this)};function ec(a){if(a.X){for(var b=0;b<a.sa.length;b++){var c=a.sa[b].M;a.ga.ja(a.sa[b].action,a.sa[b].data,function(a){a="ok"==a.s;c&&c(a)},function(){c(l)})}a.sa=[]}}
function dc(a,b){var c=a.Ma[b];a.X&&a.ga.ja("auth",{authtype:"cred",user:c.Xc,cred:c.lc},function(d){var e="ok"==d.s,d=d.d,f=k;"object"===typeof d&&d!==k&&(f=d.token);e||delete a.Ma[b];c.Rb||(c.Rb=j,c.M&&c.M(e,f))},function(){a.o("timed out on auth...")})}q.Wc=function(a,b){var c=Ea(b);G(this.U[a][c],"unlisten() called for path/queryId we're not listening on.");delete this.U[a][c];this.X&&fc(this,a,b)};
function fc(a,b,c){var d=Ea(c);a.o("Unlisten on "+b+" for "+d);b={p:b};"default"!==d&&(b.q=c);a.ga.ja("u",b,k,function(){a.o("timed out on unlisten...")})}q.L=function(a,b){this.Hb[a]=b;this.X&&gc(this,a,b)};function gc(a,b,c){b={p:b,d:c};a.o("onDisconnect",b);a.ga.ja("o",b,function(a){"ok"!==a.s&&g("onDisconnect failed: "+H(a.d))},function(){a.o("timed out on onDisconnect...")})}q.put=function(a,b,c,d){hc(this,"p",a,b,c,d)};function ic(a,b,c,d){hc(a,"m",b,c,d,h)}
function hc(a,b,c,d,e,f){c={p:c,d:d};u(f)&&(c.h=f);a.I.push({action:b,ac:c,K:e});a.Ua++;b=a.I.length-1;a.X&&jc(a,b)}function jc(a,b){var c=a.I[b].action,d=a.I[b].ac,e=a.I[b].K;a.o(c,d);a.ga.ja(c,d,function(d){a.o(c+" response",d);delete a.I[b];a.Ua--;0===a.Ua&&(a.I=[]);e&&e(d.s)},function(){a.o("timed out on put...")})}
function bc(a,b,c){var d=(new Date).getTime(),e=k;a.ga=new T(b,function(b,d){a.o("handleServerMessage",b,d);"d"===b?c(d.p,d.d):"m"===b?c(d.p,d.d,j):"t"===b?Cb=d-(new Date).getTime():zb("Unrecognized action received from server: "+H(b)+"\nAre you using the latest client?")},function(){a.X=j;e=(new Date).getTime();ec(a);for(var b in a.Ma)dc(a,b);for(var c in a.U)for(var d in a.U[c])cc(a,c,a.U[c][d]);for(c in a.Hb)gc(a,c,a.Hb[c]);for(b=0;b<a.I.length;b++)a.I[b]&&jc(a,b);a.Yb&&a.Yb()},function(){a.X=
l;kc(a);e&&(3E4<(new Date).getTime()-e&&(a.nb=1E3),e=k);var f=Math.max(0,a.nb-((new Date).getTime()-d)),f=Math.random()*f;setTimeout(function(){bc(a,b,c)},f);a.nb=Math.min(3E4,1.3*a.nb);a.B&&a.B()},function(){zb("Firebase connection was forcefully killed by the server.  This is likely due to a client/server version mismatch.  Make sure you're using the latest firebase.js.")})}
function kc(a){for(var b=0;b<a.I.length;b++){var c=a.I[b];c&&c.ac.h&&(c.K&&c.K("disconnect"),delete a.I[b],a.Ua--)}0===a.Ua&&(a.I=[])}q.o=function(){O(this.id+":",arguments)};function lc(){this.Ia=P}function U(a,b){return a.Ia.D(b)}function V(a,b,c){a.Ia=a.Ia.Za(b,c)};function mc(){this.sb=new lc;this.Q=new lc;this.na=new lc;this.Wa=new Ia}function nc(a,b,c){if(c.c())return a;if(c.i()!==k)return b;a=a||P;c.z(function(d){var d=d.name(),e=a.F(d),f=b.F(d),i=L(c,d),e=nc(e,f,i);a=a.v(d,e)});return a}mc.prototype.set=function(a,b){var c=tb();M(L(this.Wa,a),c);V(this.Q,a,b);return c};function oc(a,b,c){a=L(a.Wa,b);b=a.i();G(b!==k,"pendingPut should not be null.");b===c&&M(a,k)};function pc(){this.ra=[]}function qc(a,b){if(0!==b.length){a.ra.push.apply(a.ra,b);for(var c=0;c<a.ra.length;c++)if(a.ra[c]){var d=a.ra[c];a.ra[c]=k;var e=d.M;e(d.dc,d.Ya)}a.ra=[]}};function W(a,b,c,d){this.type=a;this.aa=b;this.N=c;this.Ya=d};function rc(a){this.u=a;this.ba=[];this.Qb=new pc}function uc(a,b,c){a.ba.push({type:b,M:c});var d=[],e=vc(a.e);a.Ca&&e.push(new W("value",a.e));for(var f=0;f<e.length;f++)if(e[f].type===b){var i=new X(a.u.j,a.u.path);e[f].N&&(i=i.A(e[f].N));d.push({M:c,dc:new S(e[f].aa,i),Ya:e[f].Ya})}qc(a.Qb,d)}function wc(a,b,c){for(var d=l,e=0;e<a.ba.length;e++){var f=a.ba[e];if(f.type===b&&f.M===c){a.ba.splice(e,1);d=j;break}}return d}rc.prototype.mb=function(a,b){b=this.Jb(a,b);xc(this,b)};
function xc(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,i=new X(a.u.j,a.u.path);b[d].N&&(i=i.A(b[d].N));i=new S(b[d].aa,i);"value"===e.type&&!i.eb()?f+="("+i.T()+")":"value"!==e.type&&(f+=" "+i.name());O(a.u.j.t.id+": event:"+a.u.path+":"+a.u.ta()+":"+f);for(f=0;f<a.ba.length;f++){var m=a.ba[f];b[d].type===m.type&&c.push({M:m.M,dc:i,Ya:e.Ya})}}qc(a.Qb,c)}function vc(a){var b=[];if(!a.Z()){var c=k;a.z(function(a,e){b.push(new W("child_added",e,a,c));c=a})}return b}
function yc(a){a.Ca||(a.Ca=j,xc(a,[new W("value",a.e)]))};function zc(a,b){rc.call(this,a);this.e=b}ia(zc,rc);zc.prototype.Jb=function(a,b){this.e=a;this.Ca&&b.push(new W("value",this.e));return b};function Ac(a,b){this.Pb=a;this.Zb=b}function Bc(a,b,c,d,e){var f=a.D(c),i=b.D(c),d=new Ac(d,e),e=Cc(d,c,f,i),i=f.g()!==i.g();if(e||i){f=c;for(c=e;f.parent()!==k;){var m=a.D(f),e=b.D(f),n=f.parent();if(L(d.Pb,n).i()){var r=b.D(n),s=[],f=Fa(f);if(m.c())m=r.P(f,e),s.push(new W("child_added",e,f,m));else if(e.c())s.push(new W("child_removed",m,f));else if(c&&(m=r.P(f,e),s.push(new W("child_changed",e,f,m))),i)m=r.P(f,e),s.push(new W("child_moved",e,f,m)),c=j;d.Zb(n,r,s)}f=n;i=l}}}
function Cc(a,b,c,d){var e,f=[];c===d?e=l:c.Z()&&d.Z()?e=c.i()!==d.i():c.Z()?(Dc(a,b,P,d,f),e=j):d.Z()?(Dc(a,b,c,P,f),e=j):e=Dc(a,b,c,d,f);(e=e||c.g()!==d.g())&&a.Zb(b,d,f);return e}
function Dc(a,b,c,d,e){var f=l,i=!L(a.Pb,b).c(),m=[],n=[],r=[],s={},fa={},v,z,w,C;v=c.Ba();w=Qa(v);z=d.Ba();for(C=Qa(z);w!==k||C!==k;){c=w===k?1:C===k?-1:w.key===C.key?0:Gb({name:w.key,fa:w.value.g()},{name:C.key,fa:C.value.g()});if(0>c)f=s[w.key],u(f)?(r.push({Sb:w,fc:m[f]}),m[f]=k):(fa[w.key]=n.length,n.push(w)),f=j,w=Qa(v);else{if(0<c)f=fa[C.key],u(f)?(r.push({Sb:n[f],fc:C}),n[f]=k):(s[C.key]=m.length,m.push(C)),f=j;else{c=b.A(C.key);if(c=Cc(a,c,w.value,C.value))w=d.P(C.key,C.value),e.push(new W("child_changed",
C.value,C.key,w)),f=j;w=Qa(v)}C=Qa(z)}if(!i&&f)return j}for(i=0;i<n.length;i++)if(s=n[i])c=b.A(s.key),Cc(a,c,s.value,P),e.push(new W("child_removed",s.value,s.key));for(i=0;i<m.length;i++)if(n=m[i])c=b.A(n.key),w=d.P(n.key,n.value),Cc(a,c,P,n.value),e.push(new W("child_added",n.value,n.key,w));for(i=0;i<r.length;i++)n=r[i].Sb,m=r[i].fc,c=b.A(m.key),w=d.P(m.key,m.value),e.push(new W("child_moved",m.value,m.key,w)),(c=Cc(a,c,n.value,m.value))&&e.push(new W("child_changed",m.value,m.key,w));return f}
;function Ec(a,b){rc.call(this,a);this.e=P;this.Jb(b,vc(b))}ia(Ec,rc);
Ec.prototype.Jb=function(a,b){var c=[],d=this.u;u(this.u.xa)&&c.push(function(a){return 0<=(a!==d.xa?a<d.xa?-1:1:0)});u(this.u.pa)&&c.push(function(a){return 0>=(a!==d.pa?a<d.pa?-1:1:0)});u(this.u.ka)&&c.push(function(a,b){return 0<=Bb(b,d.ka)});u(this.u.qa)&&c.push(function(a,b){return 0>=Bb(b,d.qa)});var e=k,f=k;if(u(this.u.ea))if(u(this.u.ka)){if(e=Fc(a,c,this.u.ea,l)){var i=a.F(e).g();c.push(function(a,b){var c=Bb(b,i);return 0>c||0===c&&a<=e})}}else if(f=Fc(a,c,this.u.ea,j)){var m=a.F(f).g();
c.push(function(a,b){var c=Bb(b,m);return 0<c||0===c&&a>=f})}for(var n=[],r=[],s=[],fa=[],v=0;v<b.length;v++){var z=b[v].N,w=b[v].aa;switch(b[v].type){case "child_added":Gc(c,z,w)&&(this.e=this.e.v(z,w),r.push(b[v]));break;case "child_removed":this.e.F(z).c()||(this.e=this.e.v(z,k),n.push(b[v]));break;case "child_changed":!this.e.F(z).c()&&Gc(c,z,w)&&(this.e=this.e.v(z,w),fa.push(b[v]));break;case "child_moved":var C=!this.e.F(z).c(),sc=Gc(c,z,w);C?sc?(this.e=this.e.v(z,w),s.push(b[v])):(n.push(new W("child_removed",
this.e.F(z),z)),this.e=this.e.v(z,k)):sc&&(this.e=this.e.v(z,w),r.push(b[v]))}}var tc=e||f;if(tc){var $c=(v=f!==k)?this.e.Tb():this.e.Vb(),ub=l,vb=l,va=this;(v?a.Db:a.z).call(a,function(a,b){ub?(n.push(new W("child_removed",va.e.F(a),a)),va.e=va.e.v(a,k)):vb&&(r.push(new W("child_added",b,a)),va.e=va.e.v(a,b));a===$c&&(vb=j);a===tc&&(ub=j);if(vb&&ub)return j})}for(v=0;v<r.length;v++)c=r[v],z=this.e.P(c.N,c.aa),n.push(new W("child_added",c.aa,c.N,z));for(v=0;v<s.length;v++)c=s[v],z=this.e.P(c.N,c.aa),
n.push(new W("child_moved",c.aa,c.N,z));for(v=0;v<fa.length;v++)c=fa[v],z=this.e.P(c.N,c.aa),n.push(new W("child_changed",c.aa,c.N,z));this.Ca&&0<n.length&&n.push(new W("value",this.e));return n};function Fc(a,b,c,d){var e=k;(d?a.Db:a.z).call(a,function(a,d){if(Gc(b,a,d)&&(e=a,c--,0===c))return j});return e}function Gc(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.g()))return l;return j};function Hc(a,b){this.t=a;this.f=b;this.Xb=b.Ia;this.Ka=new Ia}Hc.prototype.ab=function(a,b,c){var d=a.path,e=L(this.Ka,d),f=e.i();f===k&&(f={},M(e,f));var i=a.ta();i in f||(f=f||{},f[i]={},Ic(this,e,f,i,a));e=f[i].view;e||(e=this.f.Ia.D(d),e="default"===a.ta()?new zc(a,e):new Ec(a,e),f[i].view=e,(a=(a=La(L(this.Ka,d),function(a){if(a.i()&&a.i()["default"]&&a.i()["default"].view.Ca)return j}))||this.t===k)&&yc(e));uc(e,b,c)};
Hc.prototype.pb=function(a,b,c){var d=L(this.Ka,a.path),e=d.i();if(!(e===k||!f in e)){var f=a.ta();if("default"!==f)d=e[f].view,wc(d,b,c),0<d.ba.length||(e[f].C&&(e[f].C(),delete e[f].C),delete e[f]);else{var f=k,i;for(i in e)if(wc(e[i].view,b,c)){f=i;break}f&&!(0<e[f].view.ba.length)&&(e[f].C&&("default"===f&&Jc(this,d,e[f].view.Ca),e[f].C(),delete e[f].C),delete e[f])}}};function Kc(a,b,c){Ka(L(a.Ka,b),function(a){if(a=a.i())for(var b in a)yc(a[b].view)},c,j)}
function Y(a,b){var c=a.Xb,d=a.f.Ia;a.Xb=d;var e=b.toString();Bc(c,d,b,a.Ka,function(b,c,d){b.toString().substring(0,e.length)===e?(Kc(a,b,l),a.mb(b,c,d),Kc(a,b,j)):a.mb(b,c,d)});Kc(a,b,j)}Hc.prototype.mb=function(a,b,c){a=L(this.Ka,a).i();if(a!==k)for(var d in a)a[d].view.mb(b,c)};
function Ic(a,b,c,d,e){var f=l;La(b,function(a){a.i()&&a.i()["default"]&&a.i()["default"].C&&(f=j)});f||(c[d].C=Lc(a,e),"default"===d&&Ka(b,function(a){a=a.i();if(a!==k)for(var b in a)a[b].C&&(a[b].C(),delete a[b].C)}))}function Jc(a,b,c){b.z(function(b){var e=b.i();if(e&&"default"in e)G(!e["default"].C),e["default"].C=Lc(a,e["default"].view.u);else{if(e)for(var f in e)G(!e[f].C),e[f].C=Lc(a,e[f].view.u);Jc(a,b,c)}})}
function Lc(a,b){if(a.t){var c=b.path.toString(),d=a.t,e=Da(b),f=Ea(e);d.U[c]=d.U[c]||{};G(!d.U[c][f],"listen() called twice for same path/queryId.");d.U[c][f]=e;d.X&&cc(d,c,e);return y(a.t.Wc,a.t,c,Da(b))}return aa};function Mc(a){this.ha=a;this.t=new $b(this.ha,y(this.Bc,this),y(this.xc,this),y(this.Cc,this));this.vb=new Ia;this.f=new mc;this.ma=new Hc(this.t,this.f.na);this.Wb=new lc;this.Eb=new Hc(k,this.Wb);Nc(this,l)}q=Mc.prototype;q.toString=function(){return(this.ha.rb?"https://":"http://")+this.ha.host+"/"+ab(this.ha.Fa)};q.name=function(){return this.ha.Fa};
q.Bc=function(a,b,c){if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new J(a.substring(0,a.length-9)),b!==k&&Ca.test(b)&&(b=Number(b)),c=U(this.f.sb,a).yb(b);else if(c){var a=new J(a),c=U(this.f.sb,a),d;for(d in b)var e=R(b[d]),c=c.v(d,e)}else a=new J(a),c=R(b);b=this.f;d=a;e=c;V(b.sb,d,e);for(var c=U(b.Q,d),f=L(b.Wa,d),i=l,m=f;m!==k;){if(m.i()!==k){i=j;break}m=m.parent()}i?b=l:(e=nc(e,c,f),e!==c?(V(b.Q,d,e),b=j):b=l);b&&(a=Oc(this,a),Pc(this,a),a=a.path());Y(this.ma,a)};
q.xc=function(){Nc(this,j)};q.Cc=function(){Nc(this,l)};function Nc(a,b){var c=new J("/.info/connected");V(a.Wb,c,R(b));Y(a.Eb,c)}q.bb=function(a,b,c){this.t.bb(a,b,c)};q.wb=function(a,b){this.t.wb(a,b)};q.La=function(a,b,c){this.t.La(a,b,c)};q.Ja=function(a,b,c,d){this.t.Ja(a,b,c,d)};
q.ub=function(a,b,c,d){c!==k&&Ca.test(c)&&(c=Number(c));this.o("set",{path:a.toString(),value:b});var b=R(b,c),e=this.f.set(a,b),f=this;this.t.put(a.toString(),b.T(j),function(b){G("ok"===b,"put at "+a+" failed.");oc(f.f,a,e);d&&d(j)});b=Oc(this,a);Qc(this,a);Pc(this,b);Y(this.ma,b.path())};
q.update=function(a,b,c){this.o("update",{path:a.toString(),value:b});var d=U(this.f.na,a),e=j,f;for(f in b)var e=l,i=R(b[f]),d=d.v(f,i);if(e)O("update() called with empty data.  Don't do anything."),c&&c(j);else{var m=this.f.set(a,d),n=this;ic(this.t,a.toString(),b,function(b){G("ok"===b,"merge at "+a+" failed.");oc(n.f,a,m);c&&c(j)});b=Oc(this,a);Qc(this,a);Pc(this,b);Y(this.ma,b.path())}};
q.Lb=function(a,b,c){this.o("setPriority",{path:a.toString(),fa:b});var d=U(this.f.Q,a).yb(b),e=this.f.set(a,d),f=this;this.t.put(a.toString()+"/.priority",b,function(b){b="ok"===b;oc(f.f,a,e);c&&c(b)});b=Oc(this,a);Pc(this,b);Y(this.ma,b.path())};q.tb=function(a,b){this.t.L(a.toString(),b)};q.ab=function(a,b,c){".info"===F(a.path)?this.Eb.ab(a,b,c):this.ma.ab(a,b,c)};q.pb=function(a,b,c){".info"===F(a.path)?this.Eb.pb(a,b,c):this.ma.pb(a,b,c)};q.o=function(){O(this.t.id+":",arguments)};
function Rc(a,b){var c=new X(a,b);return new S(U(a.f.na,b),c)};function Qc(a,b){var c=L(a.vb,b);La(c,function(b){Sc(a,b)});Sc(a,c);Ka(c,function(b){Sc(a,b)})}function Sc(a,b){var c=b.i();if(c!==k){for(var d=-1,e=[],f=0;f<c.length;f++)if(2===c[f].status)G(d===f-1,"All SENT items should be at beginning of queue."),d=f,c[f].status=4;else if(c[f].xb(),c[f].K){var i=Rc(a,b.path());e.push(y(c[f].K,k,l,i))}-1===d?M(b,k):c.length=d+1;for(f=0;f<e.length;f++)e[f]()}}
function Tc(a,b,c,d){function e(){}a.o("transaction on "+b);var f=new X(a,b);f.Gb("value",e);var c={path:b,update:c,K:d,$b:tb(),cc:0,xb:function(){f.Fb("value",e)}},d=a.f.na,i=c.update(U(d,b).T());if(u(i)){oa("transaction failed: Data returned ",i);var m=U(a.f.Q,b).g();V(d,b,R(i,m));Y(a.ma,b);c.status=1;b=L(a.vb,b);d=b.i()||[];d.push(c);M(b,d);Uc(a)}else c.xb(),c.K&&(a=Rc(a,b),c.K(l,a))}function Uc(a,b){var c=b||a.vb;b||Vc(a,c);c.c()||(c.i()!==k?Wc(a,c):c.z(function(b){Uc(a,b)}))}
function Wc(a,b){var c=Xc(a,b);if(0!==c.length){var d=b.path();if(2!==c[0].status&&4!==c[0].status){for(var e=0;e<c.length;e++)G(1===c[e].status,"tryToSendTransactionForNode_: items in queue should all be run."),c[e].status=2,c[e].cc++;var f=U(a.f.Q,d).hash();V(a.f.Q,d,U(a.f.na,d));var i=U(a.f.Q,d).T(j),m=tb();M(L(a.f.Wa,d),m);a.t.put(d.toString(),i,function(f){a.o("transaction put response",{path:d.toString(),status:f});var i=L(a.f.Wa,d),s=i.i();G(s!==k,"tryToSendTransactionsForNode_: pendingPut should not be null.");
s===m&&(M(i,k),V(a.f.Q,d,U(a.f.sb,d)));if("ok"===f){f=[];for(e=0;e<c.length;e++)c[e].status=3,c[e].K&&(i=Rc(a,c[e].path),f.push(y(c[e].K,k,j,i))),c[e].xb();Vc(a,b);Uc(a);for(e=0;e<f.length;e++)f[e]()}else if("datastale"===f||"disconnect"===f){if("datastale"===f)for(e=0;e<c.length;e++)c[e].status=4===c[e].status?5:1;else if("disconnect"===f)for(e=0;e<c.length;e++)c[e].status=6;f=Oc(a,d);Pc(a,f);Y(a.ma,f.path())}else G(l,"Got unexpected put response to transaction: "+f)},f)}}}
function Pc(a,b){var c=b.path();V(a.f.na,c,U(a.f.Q,c));var d=Xc(a,b);if(0!==d.length){for(var e=U(a.f.na,c),f=[],i=0;i<d.length;i++){var m=Ga(c,d[i].path),n=l,r;G(m!==k,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[i].status)n=j,r="set";else if(6===d[i].status)n=j,r="disconnect";else if(1===d[i].status)if(25<=d[i].cc)n=j,r="maxretry";else{var s=d[i].update(e.D(m).T());u(s)?(oa("transaction failed: Data returned ",s),e=e.Za(m,R(s))):(n=j,r="nodata")}n&&(d[i].xb(),d[i].status=
3,d[i].K&&(n=new X(a,d[i].path),m=new S(e.D(m),n),f.push(y(d[i].K,k,l,m,r))))}d=U(a.f.Q,c).g();V(a.f.na,c,e.yb(d));Uc(a);for(i=0;i<f.length;i++)f[i]()}}function Oc(a,b){for(var c,d=a.vb;(c=F(b))!==k&&d.i()===k;)d=L(d,c),b=K(b);return d}function Xc(a,b){var c=[];Yc(a,b,c);c.sort(function(a,b){return a.$b-b.$b});return c}function Yc(a,b,c){var d=b.i();if(d!==k)for(var e=0;e<d.length;e++)c.push(d[e]);b.z(function(b){Yc(a,b,c)})}
function Vc(a,b){var c=b.i();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;M(b,0<c.length?c:k)}b.z(function(b){Vc(a,b)})};function Zc(){this.Kb={}}Zc.Ub=function(){return Zc.qc||(Zc.qc=new Zc)};var Z={Oc:function(){return Zc.Ub().Kb}};Z.repos=Z.Oc;Z.pc=function(a){var b=Q.prototype.hash;Q.prototype.hash=a;return function(){Q.prototype.hash=b}};Z.hijackHash=Z.pc;Z.ta=function(a){return a.ta()};Z.queryIdentifier=Z.ta;Z.sc=function(a){return a.j.t.U};Z.listens=Z.sc;Z.Mc=function(a){return a.j.t.ga};Z.refConnection=Z.Mc;Z.hc=T;Z.RealTimeConnection=Z.hc;T.prototype.sendRequest=T.prototype.ja;T.prototype.close=T.prototype.close;var ad=function(){var a=0,b=[];return function(){var c=(new Date).getTime()+Cb,d=c===a;a=c;for(var e=Array(8),f=7;0<=f;f--)e[f]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(c%64),c=Math.floor(c/64);G(0===c);c=e.join("");if(d){for(f=11;0<=f&&63===b[f];f--)b[f]=0;b[f]++}else for(f=0;12>f;f++)b[f]=Math.floor(64*Math.random());for(f=0;12>f;f++)c+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(b[f]);G(20===c.length,"NextPushId: Length should be 20.");
return c}}();function X(){var a,b;if(arguments[0]instanceof Mc)a=arguments[0],b=arguments[1];else{A("new Firebase",1,1,arguments.length);a=arguments[0];var c="",d="",e=l;b="";if(x(a)){var f=a.indexOf("://");0<f&&(e="https"===a.substring(0,f),a=a.substring(f+3));f=a.indexOf("/");0<f&&(c=a.substring(0,f),a=a.substring(f+1),f=a.indexOf("/"),0<f?(d=a.substring(0,f),b=a.substring(f)):(d=a,b="/"))}a={host:c,rb:e,Fa:d};b=new J(b);c=b.toString();if(!(d=!x(a.host)))if(!(d=0===a.host.length))if(!(d=!ma(a.Fa)))if(d=0!==
c.length)c&&(c=c.replace(/^\/*\.info(\/|$)/,"/")),d=!(x(c)&&0!==c.length&&!la.test(c));d&&g(Error(B("new Firebase",1,l)+"must be a valid firebase URL."));c=Zc.Ub();d=(a.rb?"https://":"http://")+a.host+"/"+a.Fa;e=c.Kb[d];e||(e=new Mc(a),c.Kb[d]=e);a=e}I.call(this,a,b)}ia(X,I);var bd=X,cd=["Firebase"],$=t;!(cd[0]in $)&&$.execScript&&$.execScript("var "+cd[0]);for(var dd;cd.length&&(dd=cd.shift());)!cd.length&&u(bd)?$[dd]=bd:$=$[dd]?$[dd]:$[dd]={};
X.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.c()?this.j.name():Fa(this.path)};X.prototype.name=X.prototype.name;X.prototype.A=function(a){A("Firebase.child",1,1,arguments.length);if(da(a))a=""+a;else if(!(a instanceof J))if(F(this.path)===k){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));sa("Firebase.child",b)}else sa("Firebase.child",a);return new X(this.j,this.path.A(a))};X.prototype.child=X.prototype.A;
X.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===k?k:new X(this.j,a)};X.prototype.parent=X.prototype.parent;X.prototype.toString=function(){A("Firebase.toString",0,0,arguments.length);return this.parent()===k?this.j.toString():this.parent().toString()+"/"+ab(this.name())};X.prototype.toString=X.prototype.toString;
X.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);E("Firebase.set",this.path);na("Firebase.set",a,l);D("Firebase.set",2,b,j);return this.j.ub(this.path,a,k,b)};X.prototype.set=X.prototype.set;
X.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);E("Firebase.update",this.path);ea(a)||g(Error(B("Firebase.update",1,l)+" must be an object containing the children to replace."));na("Firebase.update",a,l);D("Firebase.update",2,b,j);return this.j.update(this.path,a,b)};X.prototype.update=X.prototype.update;
X.prototype.ub=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);E("Firebase.setWithPriority",this.path);na("Firebase.setWithPriority",a,l);pa("Firebase.setWithPriority",2,b,l);D("Firebase.setWithPriority",3,c,j);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.j.ub(this.path,a,b,c)};X.prototype.setWithPriority=X.prototype.ub;
X.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);E("Firebase.remove",this.path);D("Firebase.remove",1,a,j);this.set(k,a)};X.prototype.remove=X.prototype.remove;
X.prototype.transaction=function(a,b){A("Firebase.transaction",1,2,arguments.length);E("Firebase.transaction",this.path);D("Firebase.transaction",1,a,l);D("Firebase.transaction",2,b,j);(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");Tc(this.j,this.path,a,b)};X.prototype.transaction=X.prototype.transaction;
X.prototype.Lb=function(a,b){A("Firebase.setPriority",1,2,arguments.length);E("Firebase.setPriority",this.path);pa("Firebase.setPriority",1,a,l);D("Firebase.setPriority",2,b,j);a!==k&&Ca.test(a)&&(a=Number(a));this.j.Lb(this.path,a,b)};X.prototype.setPriority=X.prototype.Lb;X.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);E("Firebase.push",this.path);na("Firebase.push",a,j);D("Firebase.push",2,b,j);var c=this.A(ad());"undefined"!==typeof a&&a!==k&&c.set(a,b);return c};
X.prototype.push=X.prototype.push;X.prototype.Nc=function(){A("Firebase.removeOnDisconnect",0,0,arguments.length);this.j.tb(this.path,k)};X.prototype.removeOnDisconnect=X.prototype.Nc;X.prototype.tb=function(a){A("Firebase.setOnDisconnect",1,1,arguments.length);na("Firebase.setOnDisconnect",a,l);this.j.tb(this.path,a)};X.prototype.setOnDisconnect=X.prototype.tb;
X.prototype.jc=function(a,b){A("Firebase.authAdmin",1,2,arguments.length);ua("Firebase.authAdmin",1,a);D("Firebase.authAdmin",2,b,j);this.j.bb(k,a,b)};X.prototype.authAdmin=X.prototype.jc;X.prototype.Uc=function(){this.j.wb(k)};X.prototype.unauthAdmin=X.prototype.Uc;
X.prototype.kc=function(a,b,c,d){A("Firebase.authUser",2,4,arguments.length);ta("Firebase.authUser",a);ua("Firebase.authUser",2,b);D("Firebase.authUser",3,c,j);u(d)&&"boolean"!=typeof d&&g(Error(B("Firebase.authUser",4,j)+"must be a boolean."));this.j.bb(a,b,c)};X.prototype.authUser=X.prototype.kc;X.prototype.Vc=function(a){A("Firebase.unauthUser",1,1,arguments.length);ta("Firebase.unauthUser",a);this.j.wb(a)};X.prototype.unauthUser=X.prototype.Vc;
X.prototype.La=function(a,b,c){A("Firebase.createUser",2,3,arguments.length);ta("Firebase.createUser",a);ua("Firebase.createUser",2,b);D("Firebase.createUser",3,c,j);this.j.La(a,b,c)};X.prototype.createUser=X.prototype.La;X.prototype.Ja=function(a,b,c,d){A("Firebase.setUserPassword",3,4,arguments.length);ta("Firebase.setUserPassword",a);ua("Firebase.setUserPassword",2,b);ua("Firebase.setUserPassword",3,c);D("Firebase.setUserPassword",4,d,j);this.j.Ja(a,b,c,d)};X.prototype.setUserPassword=X.prototype.Ja;
X.prototype.Rc=function(a,b,c){A("Firebase.setUserPassword",2,3,arguments.length);ta("Firebase.setUserPassword",a);ua("Firebase.setUserPassword",2,b);D("Firebase.setUserPassword",3,c,j);this.j.Ja(a,k,b,c)};X.prototype.setUserPasswordAsAdmin=X.prototype.Rc;X.enableLogging=function(a){a===j?"undefined"!==typeof console&&(yb=y(console.log,console)):yb=a?a:k};X.TEST_HOOKS=Z;})();
